### ISSUE TITLE
关于css样式前缀的问题

### ISSUE THREAD

**Issue by panchaoco** [vue-styled-components/core#19]
### Describe the bug

生成的css样式，比如display: flex; 并没有加上浏览器的前缀

### To reproduce

![image](https://github.com/user-attachments/assets/7522576c-e0ec-4d48-b5ee-1ad29a6324d1)

### Expected behavior

期望可以加上浏览器前缀，虽然浏览器如今已经比较新了，但还是需要考虑有些浏览器不兼容或者需要前缀支持的情况

**Comment by akinoccc** [comment]
我今晚看看

**Comment by panchaoco** [comment]
谢谢，应该有挺多方便加浏览器前缀的三方库，因为我在生产用了你的包，所以非常感谢你的及时回复

**Comment by akinoccc** [comment]
Release v1.4.10
- [自动为 CSS styles 添加浏览器私有前缀](https://vue-styled-components.com/guide/advances/auto-prefix)
- [Nest CSS 支持版本较低的浏览器](https://vue-styled-components.com/guide/advances/nest-css)

**Comment by panchaoco** [comment]
> Release v1.4.0
> 
> * [自动为 CSS styles 添加浏览器私有前缀](https://vue-styled-components.com/guide/advances/auto-prefix)
> * [Nest CSS 支持版本较低的浏览器](https://vue-styled-components.com/guide/advances/nest-css)

你太优秀了，哈哈

**Comment by akinoccc** [comment]
@panchaoco reopen？还有问题吗

**Comment by panchaoco** [comment]
> reopen

没有了，我以为是需要你来close， 才打开的，哈

**Comment by akinoccc** [comment]
> > reopen
> 
> 没有了，我以为是需要你来close， 才打开的，哈

没问题自己关就行，没那么讲究😂
